# Broadcasting

Broadcasting explains the way NumPy handles arrays of various shapes when performing arithmetic operations.​Element-to-element operations cannot be performed on two arrays if their dimensions are different. NumPy still allows operations on arrays of different shape arrays due to the broadcasting feature. In order for the smaller array and the larger array to have similar shapes, they are broadcast to the same size.

import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print(a) 
print('\n')  
   
print('Second array:') 
print(b) 
print('\n')  
   
print('First Array + Second Array' )
print( a + b)

## Structured arrays
Various types and sizes of data are organised using it. Fields are the type of data containers used by structure arrays. Any type and amount of data can be contained in each data field. Dot notation can be used to access an array's elements.

-Structured array properties

The array's structs all have the same number of fields. The names of the fields in all structs are the same.

In [6]:
#Python program to demonstrate
# Structured array
import numpy as np
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)], 
             dtype=[('name', (np. str_, 10)), ('age', np.int32), ('weight', np.float64)])
print(a)
print(type(a))


[('Sana', 2, 21.) ('Mansi', 7, 29.)]
<class 'numpy.ndarray'>


## Statistical Functions
Numpy includes a number of statistical functions that can be used to perform statistical data analysis. Statistics is concerned with gathering and analysing data. NumPy includes a number of statistical functions for analysing statistical data.

np.amin()- Minimum value of the element along a specified axis.
np.amax()- Maximum value of the element along a specified axis.
np.mean()- Mean value of the data set.
np.median()- Median value of the data set.
np.ptp()- Range of values along an axis(peak to peak).
np.std()- Standard deviation
np.var() – Variance.
np.average()- Weighted average
np.percentile()- nth percentile of data along the specified axis.

## Mean -  Compute the arithmetic mean along the specified axis. np.mean([1,2,3,4,5])
Median - Compute the median along the specified axis. np.median([1,5,2,3,4])
Range -  Compute the median along the specified axis. np.ptp([1,5,2,3,4])
Standard deviation is the square root of the average of squared deviations from mean. The function used for this i np.std().  np.std([1,2,3,4])

Variance is the average of squared deviations, i.e., mean(abs(x - x.mean())**2).

Or, standard deviation is the square root of variance. np.var([1,2,3,4])

In [7]:
import numpy as np
arr = np.arange(0,10)

In [8]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr * arr


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_14900\2878212635.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_14900\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [15]:
np.mean([1,2,3,4,5])

3.0

In [16]:
 np.median([1,5,2,3,4])

3.0

In [17]:
np.ptp([1,5,2,3,4])

4

In [19]:
 np.std([1,2,3,4])

1.118033988749895

In [28]:
np.var([1,2,3,4])

1.25

In [29]:

x =np.array([1,2,3,4])
a= np.mean(abs(x-x.mean()**2))
print(a)

3.75
