In [5]:
import numpy as np
arr = np.array([1,2,3,4])

print(arr.dtype)
print(arr)

int32
[1 2 3 4]


# 0-D Arrays

In [8]:
arr = np.array(42)
print(arr)

42


# 1-D Arrays

In [12]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [15]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 3-D Arrays

In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


 # Check Number of Dimensions? 

In [19]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)




0
1
2
3


#  Numpy.save() 
## The save() and load() functions accept an additional boolean parameter allow_pickle in python is used to serialize saving to or reading from a disk file.

In [22]:
a = np.array([1,2,3,4,5])
np.save('outfile',a)

In [24]:
b = np.load('outfile.npy')
print(b)

[1 2 3 4 5]


# Savetxt()

In [32]:
import numpy as np

a = np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)
print(type(b))
print(b.dtype)


<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


# Indexing:-

## 1. Indexing using index Arrays

In [36]:
arr = np.arange(1,10,2)   # range function is not supported in numpy .
print("Elements of array:",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ", arr1)

Elements of array: [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


# Indexing in 1 dimension

In [40]:
arr1 = np.arange(4)
print("Array arr1", arr1)
print("Element at index 0 of arri is", arr1[0])
print("Element at index 1 of arri is", arr1[1])

Array arr1 [0 1 2 3]
Element at index 0 of arri is 0
Element at index 1 of arri is 1


# Indexing in 2 dimension

arr = np.arange(12)
arr1 = arr.reshape(3,4)
print("Array arr1:\n", arr1)
print("Element at eth row and eth column of arr1 is:", arr1[0,0])
print("Element at 1th row and 2nd 2olumn of arr1 is:", arr1[1,2])

# Indexing in 3 Dimension

In [46]:
arr = np.arange(12)
arr1 = arr.reshape(2,2,3)   # x,y,z plane
print("Array arr1:\n", arr1)
print("Element:", arr1[1,0,2])     # first display matrix second display row and third display column.


Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 8


# Slicing an Array

# Slicing 1D Numpy Array


In [48]:
arr = np.arange(6)
print("array arr:",arr)
print("sliced element of array:", arr[1:5])
print("sliced element of array:", arr[-5:-1])

array arr: [0 1 2 3 4 5]
sliced element of array: [1 2 3 4]
sliced element of array: [1 2 3 4]


# Slicing 2D Numpy Array

In [49]:
arr = np.arange(12)
arr1 =arr.reshape(3,4)
print("Array arr1: \n",arr1)
print("\n")
print("Element of 1st row and 1st column upto last column \n",arr1[1:,1:4])

Array arr1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Element of 1st row and 1st column upto last column 
 [[ 5  6  7]
 [ 9 10 11]]
